package org.val.win.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-16T14:32:20.259+02:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "P7ServiceImplService",
                  wsdlLocation = "file:/Users/v.w/Documents/GitHub/Projet_7_Webapp/src/main/java/org/val/win/service.wsdl",
                  targetNamespace = "http://impl.service.win.val.org/")
public class P7ServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.win.val.org/", "P7ServiceImplService");
    public final static QName P7ServiceImplPort = new QName("http://impl.service.win.val.org/", "P7ServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/v.w/Documents/GitHub/Projet_7_Webapp/src/main/java/org/val/win/service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(P7ServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/v.w/Documents/GitHub/Projet_7_Webapp/src/main/java/org/val/win/service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public P7ServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public P7ServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public P7ServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public P7ServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public P7ServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public P7ServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns P7Service
     */
    @WebEndpoint(name = "P7ServiceImplPort")
    public P7Service getP7ServiceImplPort() {
        return super.getPort(P7ServiceImplPort, P7Service.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns P7Service
     */
    @WebEndpoint(name = "P7ServiceImplPort")
    public P7Service getP7ServiceImplPort(WebServiceFeature... features) {
        return super.getPort(P7ServiceImplPort, P7Service.class, features);
    }

}
