
package org.val.win.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.val.win.model.bean.*;
import org.val.win.model.exception.NotFoundException_Exception;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-16T14:32:20.182+02:00
 * Generated source version: 3.2.6
 *
 */
public final class P7Service_P7ServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.win.val.org/", "P7ServiceImplService");

    private P7Service_P7ServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = P7ServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        P7ServiceImplService ss = new P7ServiceImplService(wsdlURL, SERVICE_NAME);
        P7Service port = ss.getP7ServiceImplPort();

        {
        System.out.println("Invoking retardEmprunt...");
        Emprunt _retardEmprunt_arg0 = null;
        port.retardEmprunt(_retardEmprunt_arg0);


        }
        {
        System.out.println("Invoking getListDispo...");
        OuvrageArray _getListDispo__return = port.getListDispo();
        System.out.println("getListDispo.result=" + _getListDispo__return);


        }
        {
        System.out.println("Invoking getListEmprunt...");
        EmpruntArray _getListEmprunt__return = port.getListEmprunt();
        System.out.println("getListEmprunt.result=" + _getListEmprunt__return);


        }
        {
        System.out.println("Invoking utilisateurLogin...");
        java.lang.String _utilisateurLogin_arg0 = "";
        java.lang.String _utilisateurLogin_arg1 = "";
        Utilisateur _utilisateurLogin__return = port.utilisateurLogin(_utilisateurLogin_arg0, _utilisateurLogin_arg1);
        System.out.println("utilisateurLogin.result=" + _utilisateurLogin__return);


        }
        {
        System.out.println("Invoking getOuvrage...");
        int _getOuvrage_arg0 = 0;
        try {
            Ouvrage _getOuvrage__return = port.getOuvrage(_getOuvrage_arg0);
            System.out.println("getOuvrage.result=" + _getOuvrage__return);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking emprunt...");
        Emprunt _emprunt_arg0 = null;
        Utilisateur _emprunt_arg1 = null;
        Ouvrage _emprunt_arg2 = null;
        try {
            port.emprunt(_emprunt_arg0, _emprunt_arg1, _emprunt_arg2);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getListEmpruntUtilisateur...");
        Utilisateur _getListEmpruntUtilisateur_arg0 = null;
        EmpruntArray _getListEmpruntUtilisateur__return = port.getListEmpruntUtilisateur(_getListEmpruntUtilisateur_arg0);
        System.out.println("getListEmpruntUtilisateur.result=" + _getListEmpruntUtilisateur__return);


        }
        {
        System.out.println("Invoking getListOuvrage...");
        OuvrageArray _getListOuvrage__return = port.getListOuvrage();
        System.out.println("getListOuvrage.result=" + _getListOuvrage__return);


        }
        {
        System.out.println("Invoking prolongationEmprunt...");
        Emprunt _prolongationEmprunt_arg0 = null;
        port.prolongationEmprunt(_prolongationEmprunt_arg0);


        }
        {
        System.out.println("Invoking fermerEmprunt...");
        Emprunt _fermerEmprunt_arg0 = null;
        try {
            port.fermerEmprunt(_fermerEmprunt_arg0);

        } catch (NotFoundException_Exception e) {
            System.out.println("Expected exception: NotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUtilisateur...");
        int _getUtilisateur_arg0 = 0;
        Utilisateur _getUtilisateur__return = port.getUtilisateur(_getUtilisateur_arg0);
        System.out.println("getUtilisateur.result=" + _getUtilisateur__return);


        }

        System.exit(0);
    }

}
