
package org.val.win.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-09-16T14:32:20.240+02:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://contract.service.win.val.org/")
public class NotFoundException_Exception extends Exception {

    private NotFoundException notFoundException;

    public NotFoundException_Exception() {
        super();
    }

    public NotFoundException_Exception(String message) {
        super(message);
    }

    public NotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NotFoundException_Exception(String message, NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public NotFoundException_Exception(String message, NotFoundException notFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
